# Generated by Django 5.1.3 on 2024-12-15 17:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_user_phone_alter_user_country"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                default="/profile_img/ava_001.png",
                null=True,
                upload_to="profile_img/",
                verbose_name="Аватар",
            ),
        ),
    ]
