# Generated by Django 5.1.3 on 2025-01-04 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0004_alter_user_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("Managers", "Can view and block users")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
    ]
