# Generated by Django 5.1.3 on 2025-01-06 01:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0006_alter_user_options"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="groups",
        ),
        migrations.AddField(
            model_name="user",
            name="groups",
            field=models.CharField(
                blank=True,
                choices=[("Менеджер", "manager"), ("Пользователь", "user")],
                max_length=250,
                null=True,
                verbose_name="Роль",
            ),
        ),
    ]
