# Generated by Django 5.1.3 on 2025-01-06 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0009_alter_user_options_remove_user_groups_user_groups"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Менеджер", "Менеджер"), ("Пользователь", "Пользователь"), ("Запущена", "Запущена")],
                max_length=250,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
