# Generated by Django 5.1.3 on 2025-01-06 02:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0010_user_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("managers", "Can view and block users"), ("blocked_user", "Is blocked")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AddField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Блокировкка пользователя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="status",
            field=models.CharField(
                blank=True,
                choices=[("Менеджер", "Менеджер"), ("Пользователь", "Пользователь")],
                max_length=250,
                null=True,
                verbose_name="Статус",
            ),
        ),
    ]
