# Generated by Django 5.1.3 on 2025-01-06 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0011_alter_user_options_user_is_blocked_alter_user_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "permissions": [("managers", "Can view and block users")],
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="is_blocked",
            field=models.BooleanField(default=False, verbose_name="Блокировка пользователя"),
        ),
    ]
