# Generated by Django 5.1.3 on 2024-12-05 16:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.CharField(max_length=150, unique=True, verbose_name="Email")),
                ("full_name", models.CharField(max_length=150, verbose_name="Ф.И.О.")),
                ("notes", models.TextField(blank=True, null=True, verbose_name="Комментарий")),
            ],
            options={
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
                "ordering": ["email"],
            },
        ),
        migrations.CreateModel(
            name="Home",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("total_mailout", models.IntegerField(default=0, verbose_name="Количество всех рассылок")),
                ("total_active", models.IntegerField(default=0, verbose_name="Количество активных рассылок")),
                ("total_users", models.IntegerField(default=0, verbose_name="Количество уникальных получателей")),
            ],
            options={
                "verbose_name": "статистика",
                "verbose_name_plural": "статистика",
                "ordering": ["total_mailout", "total_active", "total_users"],
            },
        ),
        migrations.CreateModel(
            name="Message",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subject", models.CharField(max_length=250, verbose_name="Тема")),
                ("message", models.TextField(blank=True, null=True, verbose_name="Сообщение")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="Дата создания сообщения")),
            ],
            options={
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
                "ordering": ["created_at"],
            },
        ),
        migrations.CreateModel(
            name="Mailout",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("subscribed_at", models.DateTimeField(auto_now_add=True, verbose_name="Рассылка создана")),
                ("sent_at", models.DateTimeField(auto_now_add=True, verbose_name="Рассылка завершена")),
                ("is_active", models.BooleanField(default=False, verbose_name="Рассылка запущена")),
                (
                    "status",
                    models.CharField(
                        choices=[("Создана", "Created"), ("Завершена", "Completed"), ("Запущена", "In progress")],
                        max_length=250,
                        verbose_name="Статус рассылки",
                    ),
                ),
                ("clients", models.ManyToManyField(to="mailout.clients")),
                ("message", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailout.message")),
            ],
            options={
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
                "ordering": ["sent_at", "status"],
            },
        ),
    ]
