# Generated by Django 5.1.3 on 2024-12-08 03:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailout", "0003_message_service_user"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameField(
            model_name="clients",
            old_name="service_user",
            new_name="owner",
        ),
        migrations.RenameField(
            model_name="message",
            old_name="service_user",
            new_name="owner",
        ),
        migrations.AddField(
            model_name="mailout",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Пользователь",
            ),
        ),
    ]
