# Generated by Django 5.1.3 on 2024-12-08 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailout", "0004_rename_service_user_clients_owner_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailout",
            name="status",
            field=models.CharField(
                choices=[("Created", "Создана"), ("Completed", "Завершена"), ("In progress", "Запущена")],
                max_length=250,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
