# Generated by Django 5.1.3 on 2024-12-08 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailout", "0005_alter_mailout_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="mailout",
            options={
                "ordering": ["message", "sent_at", "status"],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
    ]
