# Generated by Django 5.1.3 on 2024-12-08 13:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailout", "0006_alter_mailout_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailout",
            name="clients",
            field=models.ManyToManyField(related_name="mailout", to="mailout.clients"),
        ),
        migrations.AlterField(
            model_name="mailout",
            name="status",
            field=models.CharField(
                choices=[("Создана", "Создана"), ("Завершена", "Завершена"), ("Запущена", "Запущена")],
                max_length=250,
                verbose_name="Статус рассылки",
            ),
        ),
    ]
