# Generated by Django 5.1.3 on 2024-12-08 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailout", "0007_alter_mailout_clients_alter_mailout_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mailout",
            name="is_active",
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name="Рассылка запущена"),
        ),
        migrations.AlterField(
            model_name="mailout",
            name="sent_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Рассылка завершена"),
        ),
        migrations.AlterField(
            model_name="mailout",
            name="subscribed_at",
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name="Рассылка создана"),
        ),
        migrations.CreateModel(
            name="Attempt",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("emailed_at", models.DateTimeField(auto_now_add=True, verbose_name="Попытка рассылки")),
                (
                    "status",
                    models.CharField(
                        choices=[("Успешно", "Успешно"), ("Не успешно", "Не успешно")],
                        max_length=250,
                        verbose_name="Статус рассылки",
                    ),
                ),
                ("server_message", models.TextField(blank=True, null=True, verbose_name="Ответ почтового сервера")),
                ("mailout", models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to="mailout.mailout")),
            ],
            options={
                "verbose_name": "попытка рассылки",
                "verbose_name_plural": "попытки рассылки",
                "ordering": ["emailed_at", "status"],
            },
        ),
    ]
