# Generated by Django 5.1.3 on 2024-12-11 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailout", "0008_alter_mailout_is_active_alter_mailout_sent_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="total_active",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Количество активных рассылок"),
        ),
        migrations.AlterField(
            model_name="home",
            name="total_mailout",
            field=models.CharField(blank=True, max_length=250, null=True, verbose_name="Количество всех рассылок"),
        ),
        migrations.AlterField(
            model_name="home",
            name="total_users",
            field=models.CharField(
                blank=True, max_length=250, null=True, verbose_name="Количество уникальных получателей"
            ),
        ),
    ]
