# Generated by Django 5.1.3 on 2024-12-13 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("mailout", "0009_alter_home_total_active_alter_home_total_mailout_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="home",
            name="total_active",
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Количество активных рассылок"),
        ),
        migrations.AlterField(
            model_name="home",
            name="total_mailout",
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name="Количество всех рассылок"),
        ),
        migrations.AlterField(
            model_name="home",
            name="total_users",
            field=models.IntegerField(
                blank=True, default=0, null=True, verbose_name="Количество уникальных получателей"
            ),
        ),
    ]
