# Generated by Django 5.1.3 on 2025-01-02 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailout", "0012_alter_home_total_active_alter_home_total_mailout_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clients",
            options={
                "ordering": ["email"],
                "permissions": [("can_edit_client_info", "Can edit client's information")],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailout",
            options={
                "ordering": ["message", "sent_at", "status"],
                "permissions": [("can_edit_mailout", "Can edit mailout")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "permissions": [("can_edit_messages", "Can edit messages")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
    ]
