# Generated by Django 5.1.3 on 2025-01-03 21:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("mailout", "0014_alter_clients_email"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="clients",
            options={
                "ordering": ["email"],
                "permissions": [("can_view_client_info", "Can view client's information")],
                "verbose_name": "получатель",
                "verbose_name_plural": "получатели",
            },
        ),
        migrations.AlterModelOptions(
            name="mailout",
            options={
                "ordering": ["message", "sent_at", "status"],
                "permissions": [("can_view_mailout", "Can view mailout")],
                "verbose_name": "рассылка",
                "verbose_name_plural": "рассылки",
            },
        ),
        migrations.AlterModelOptions(
            name="message",
            options={
                "ordering": ["created_at"],
                "permissions": [("can_view_messages", "Can view messages")],
                "verbose_name": "сообщение",
                "verbose_name_plural": "сообщения",
            },
        ),
    ]
